nekoyume/nekoyume

.gitignore, README.rst, nekoyume/app.py
=> Remove secret key in the code and generate it automatically

nekoyume/models.py
=> Change using datetime.datetime.now to using utcnow

nekoyume/cli.py, nekoyume/models.py
=> Add `doctor` and `repair` command to cli

nekoyume/cli.py
=> Add translation script to `nekoyume init` 

nekoyume/items.py
Code        Food Name             Recipe
FRRC	FriedRice		RKST RICE OLIV
CFRC	ChickenFriedRice	FRRC CHKN CHKN
EFRC	EggFriedRice		FRRC EGGS EGGS
MFRC	MeatFriedRice	FRRC EGGS EGGS
MAFR	MasterFriedRice	CFRC EFRC MFRC
BRED	Bread			WHET EGGS OLIV
EGTR	EggTart		        BRED EGGS EGGS
FREG	FriedEgg		        EGGS OLIV RKST
=> Add Some Food Recipe

nekoyume/game.py, nekoyume/templates/dashboard.html, nekoyume/translations/ko/LC_MESSAGES/messages.po, tests/game_test.py
=> Implement export private key menu

nekoyume/items.py
Fixed MasterFriedRice arg from HPFood to HPMaxFood
Rearranged classes into 2 tiers of food (not including HPMaxFood) for improved readability.
Fixed typo in oyakodon and steakdon.
Added 3 recipes:
SteakSandwich(SKSW) - BRED, STEK, 20HP Food
MeatLoversBurger(MLBG) - FCHK, FCHK, MPLT, HPMaxFood
PoorMansPizza(PMPZ) - MEAT, WHET, OLIV, 10HP Food
=> Add 3 food recipes, rearrange recipes list, fix typos.

docs/roadmap.md
I fixed errata.
It's related to [#59](https://github.com/nekoyume/nekoyume/issues/59)
=> Fix errata

docs/white_paper.md
I Fixed errata of `docs/white_paper.md`
Please review this.
It is related of #59
=> Fix errata of `docs/white_paper.md`

docs/white_paper.md
I fixed grammatical mistakes and made some expressions look better.
Please check this!
It's related to [#59](https://github.com/nekoyume/nekoyume/issues/59)
=> Fix errata and grammatical mistakes

nekoyume/translations/ko/LC_MESSAGES/messages.po
I fixed some grammatical error and awkward expressions.
Please review this!
It's related to #59[ ](https://github.com/nekoyume/nekoyume/issues/59)
=> Fix errata and change some expressions

README.rst
=> using `venv` instead of `virtualenv`

setup.py
coincurve fixed this issue in https://github.com/ofek/coincurve/commit/971d07fe79ec36b5b60ae103e40ce32f8f61efc4
=> Fix macOS install problem caused by coincurve (#72)

nekoyume/api.py, nekoyume/app.py, nekoyume/cli.py, nekoyume/game.py, nekoyume/items.py, nekoyume/models.py, nekoyume/tasks.py, setup.cfg, setup.py, tests/conftest.py, tests/game_test.py, tests/models_test.py, tests/tasks_test.py
- apply flake8-import-order-spoqa
=> Fix import order style

nekoyume/game.py, nekoyume/translations/ja/LC_MESSAGES/messages.po
Two things fixed to make japanese translation run
1. Add 'ja' to locale
1. Fix wrong .po syntax
=> Fix japanese translation

README.rst, hooks/pre-commit, hooks/pre-push
=> Add commit, push hook

README.rst
=> fix wrong hooks path

nekoyume/cli.py, nekoyume/models.py
In order to make the default seed URL more configurable, this patch extracts out the default seed URL (i.e., `http://seed.nekoyu.me`) from *models.py* to *cli.py* file.
=> Extract out the default seed URL from models.py to cli.py

docs/conf.py, setup.py
=> 0.1.2 version update

.circleci/config.yml, docker-compose.yml, nekoyume/models.py
=> Fix docker compose running problem & running in circleci

nekoyume/api.py, nekoyume/app.py, nekoyume/battle/__main__.py, nekoyume/battle/characters.py, nekoyume/battle/components/__init__.py, nekoyume/battle/components/bag.py, nekoyume/battle/components/behaviors/__init__.py, nekoyume/battle/components/behaviors/aggro.py, nekoyume/battle/components/behaviors/skills/__init__.py, nekoyume/battle/components/buff.py, nekoyume/battle/components/stats.py, nekoyume/battle/simul.py, nekoyume/cli.py, nekoyume/game.py, nekoyume/items/__init__.py, nekoyume/items/armors.py, nekoyume/items/base.py, nekoyume/items/foods.py, nekoyume/items/heads.py, nekoyume/items/weapons.py, nekoyume/shell.py, nekoyume/tables/__init__.py, nekoyume/tasks.py
- Use relative import style
- Add missing import `Armor` in items.py
=> Use relative import instead of absolute import

README.rst, docker-compose.yml, nekoyume/cli.py
=> Rename “neko” command to “mine”

.editorconfig, app.json
- Introduced [*.editorconfig*][1] so that the trivial code style between collaborators become consistent.
- Fixed *app.json*'s indentation mixed of 2 and 4 spaces.
[1]: https://editorconfig.org/
=> Introduce .editorconfig

.gitignore, README.rst
=> change virtualenv name

nekoyume/models.py
Merged multiple except statements into one.
=> Merge multiple except statements into one

nekoyume/models.py
Block.create can be reutrn `None`
=> Fix wrong invalid typehint

nekoyume/models.py
=> Change difficulty

nekoyume/api.py, nekoyume/block.py, nekoyume/broadcast.py, nekoyume/cli.py, nekoyume/game.py, nekoyume/move.py, nekoyume/node.py, nekoyume/tasks.py, setup.py, tests/api_test.py, tests/block_test.py, tests/broadcast_test.py, tests/move_test.py, tests/node_test.py, tests/tasks_test.py
=> Seperate broadcast

nekoyume/move.py, nekoyume/util.py, tests/block_test.py, tests/move_test.py
resolved #135 
this pr is from #137
=> Raise InvalidMoveError when block confirmed not yet

.circleci/config.yml, deployment.yaml, nekoyume/battle/characters.py, nekoyume/battle/components/behaviors/skills/__init__.py, nekoyume/battle/components/stats.py, nekoyume/battle/simul.py, nekoyume/battle/status/base.py, nekoyume/battle/status/skills.py, nekoyume/battle/status/stats.py, nekoyume/game.py, nekoyume/move.py, nekoyume/static/common.css, nekoyume/static/game.css, nekoyume/static/items.css, nekoyume/tables/__init__.py, nekoyume/tables/monster_skills.tsv, nekoyume/tables/monsters.tsv, nekoyume/tables/npc.tsv, nekoyume/tables/skills.tsv, nekoyume/tables/stats.tsv, nekoyume/tables/zone.tsv, nekoyume/templates/basic_info.html, nekoyume/templates/first_class.html, nekoyume/templates/game.html, nekoyume/templates/layout.html, nekoyume/templates/login.html, nekoyume/templates/new.html, nekoyume/templates/status.html, nekoyume/user.py, tests/game_test.py
- Create user with avatar name
- Select job
- Select zone
- Unity
=> Apply unity

nekoyume/move.py
fix broken master branch build
=> Set ensure_block new move

.circleci/config.yml, deployment.yaml, nekoyume/app.py, nekoyume/cli.py, setup.py
- Use commit hash when build docker image
- CircleCI workflows
- Sentry config for logging
=> Update dev settings

.circleci/config.yml, setup.py
requests, sentry raise version conflict
=> Avoid version conflict

nekoyume/tables/zone.tsv, nekoyume/templates/game.html
The game maintains a queue of battle result, and renders it one by one. When queue size < 4, we send another hackAndSlash or sleep request based on player health.
=> Change to Idle Mode

nekoyume/api.py, nekoyume/block.py, tests/api_test.py, tests/block_test.py
Avoid `JSONDecodeError` in `Block.sync` when calling Node.api return null
fixed #165
=> Return 404 status code for avoid JSONDecodeError

nekoyume/api.py, nekoyume/block.py, nekoyume/broadcast.py, nekoyume/cli.py, nekoyume/game.py, nekoyume/tasks.py, tests/api_test.py, tests/block_test.py, tests/broadcast_test.py, tests/game_test.py, tests/tasks_test.py
resolve #149 
plsease review last commit only
=> Refactoring broadcast

.circleci/config.yml, Dockerfile, config.yaml, deployment.yaml, nekoyume/api.py, nekoyume/block.py, nekoyume/move.py, nekoyume/util.py, setup.py, tests/api_test.py, tests/util_test.py
- Use commit hash for docker image tag, check node version
- Avoid ValueError when deserialize timestamp
=> Fix deserialize
